package com.example.spring3.infrastructure.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.example.spring3.domain.entity.Document;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

@Data
@DynamoDBTable(tableName = "Document")
@NoArgsConstructor
public class DocumentEntity extends Document {
  @DynamoDBHashKey(attributeName = "user_id")
  private String userId;
  @DynamoDBAutoGeneratedKey
  @Getter(onMethod_ = {@DynamoDbSortKey})
  @DynamoDBAttribute(attributeName = "id")
  private String id;
  @DynamoDBIndexRangeKey(attributeName = "document_type",
      localSecondaryIndexName = "UserTypeIndex")
  private String documentType;
  @DynamoDBAttribute(attributeName = "bucket")
  private String bucket;
  @DynamoDBAttribute(attributeName = "extension")
  private String extension;
  @DynamoDBAttribute(attributeName = "path")
  private String path;
  @DynamoDBAttribute(attributeName = "url")
  private String url;
  @DynamoDBAttribute(attributeName = "start_date")
//  @DynamoDBTypeConverted(converter = InstantConverter.class)
  private String startDate;
  @DynamoDBAttribute(attributeName = "end_date")
//  @DynamoDBTypeConverted(converter = InstantConverter.class)
  private String endDate;
}
